src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Id__c</fullName>
        <label>Track_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomPaginationDemo.cls
public with sharing class CustomPaginationDemo
{
Public Track__C track{get;set;}
   
public List<ContactWrapper> lstWrapper {get;set;}
public List<ContactWrapper> lstSetController{get;set;}

public List<Track__C> selectedTracks{get;set;}
public List<Track__C> tracksToUpdate{get;set;}

CustomIterable obj;

    public CustomPaginationDemo() 
    {
        track = new Track__C();
        lstWrapper =  new List<ContactWrapper>();
        lstSetController = new List<ContactWrapper>();

        List<Track__C> lstTrack = [Select id,Name,Album__c,Genre__C,Track_Id__c From Track__C];
        
        for(Track__C cont : lstTrack )
        {
            lstWrapper.add(new ContactWrapper(cont ,false));
        }

        obj = new CustomIterable (lstWrapper); 
        obj.setPageSize = 5;
        next();         
    }
    
    public pageReference Add(){
        selectedTracks = new List<Track__C>();
        tracksToUpdate = new List<Track__C>();
       for(ContactWrapper wrapTrackObj : lstSetController) {
        
        if(wrapTrackObj.isSelected == true) {
            selectedTracks.add(wrapTrackObj.cont);
          }
          system.debug('Selected Tarcks:::'+selectedTracks);
          
        } 
        
        for(Track__c cc: [Select id,Name,Album__c,Genre__C,Track_Id__c From Track__C where id IN: selectedTracks] ){            
        
            cc.Album__c = track.album__C;
            tracksToUpdate.add(cc);
        }
      
        upsert tracksToUpdate;
        
        pageReference pgref = New pageReference('/apex/musicHome');
        pgref.setRedirect(false);
        return pgRef;
        
    }
    
        public Boolean hasNext {
            get 
            {
                return obj.hasNext();
            }
            set;
        }
        
        public Boolean hasPrevious {
            get 
            {
                return obj.hasPrevious();
            }
            set;
        }
        
        public void next() 
        {
            lstSetController = obj.next();
        }
        
        public void previous() 
        {
            lstSetController = obj.previous();
        }
    
}