src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Users</label>
        <referenceTo>Users__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Users__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>User ID-{0000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/musicHome_Controller.cls
public class musicHome_Controller {
    public String SearchText{get;set;} 
	public String option {get;set;}
    public List<Album__c> lstAlbums{get;set;}
    Public musicHome_Controller(Apexpages.StandardController controller){ 
    }
    //It is for Search Method
    public pageReference SearchAlbums(){        
    if(option == 'Name'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }     
   if(option == 'Track__c.Name__C')
    {
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+searchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }    
    if(option == 'genre__r.Name__c'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+searchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }
    if(option == 'User__r.Name__c'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }    
    if(option == 'Album_rating__C'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }       
       else
       return null;       
    }
}