src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Cover_Photo__c</fullName>
        <label>Cover Photo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Users</label>
        <referenceTo>Users__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <label>Track Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks (User Album)</relationshipLabel>
        <relationshipName>Tracks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Users__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>User ID-{0000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HomeDup_Controller.cls
Public class HomeDup_Controller{

public string searchText{get;set;}
public string option{get;set;}
public string getSelected;
public string getValue;
public Integer trackCount{get;set;}

Public HomeDup_Controller(){
    
    getSelected = ApexPages.CurrentPage().GetParameters().get('query');
    getValue = ApexPages.CurrentPage().GetParameters().get('s_by');      

}


     //Search Album Method
    public pageReference Search(){
        if(option == 'Name')
        {
           pageReference pgRef = new pageReference('/apex/HomeDupl?query='+SearchText+'&s_by='+option);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
          
           return pgRef;
        }
        
        if(option == 'Track__c.Name__C')
        {
           pageReference pgRef = new pageReference('/apex/HomeDupl?query='+SearchText+'&s_by='+option);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
          
           return pgRef;
        }
        
        if(option == 'genre__r.Name__c')
        {
           pageReference pgRef = new pageReference('/apex/HomeDupl?query='+SearchText+'&s_by='+option);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
          
           return pgRef;
        }
        
        if(option == 'User__r.Name__c')
        {
           pageReference pgRef = new pageReference('/apex/HomeDupl?query='+SearchText+'&s_by='+option);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
          
           return pgRef;
        }
        
        if(option == 'Album_rating__C')
        {
           pageReference pgRef = new pageReference('/apex/HomeDupl?query='+SearchText+'&s_by='+option);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
          
           return pgRef;
        }
        
        
    else {
        return NULL;
    }
    }
    
    public ApexPages.StandardSetController setCon {
        get {
         if(SetCon == NULL){
           
            if(getSelected!='' || getSelected!=NULL && getValue == 'Name')
            {
                
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,Name,Cover_Photo__c,Album_Rating__c,Rating__c,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE Name LIKE : getSelected+'%']));
            }
           
           /* if(getSelected!='' || getSelected!=NULL && getValue == 'Track__c.Name__C"')
            {
                
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,name,Rating__c,(Select id,Album__C,User_Album__c From Tracks__r) from Album__C where id in (select Album__c From Track__C where Track_Name__C LIKE :getSelected+'%']));
            }*/
            
           if(getSelected!='' || getSelected!=NULL && getValue == 'genre__r.Name__c')
            {
                  setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,Name,Cover_Photo__c,Rating__c,Album_Rating__c,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE genre__r.Name__c LIKE : getSelected+'%']));
            
            }    
            
           if(getSelected!='' || getSelected!=NULL && getValue == 'User__r.Name__c')
            {
                  setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,Name,Cover_Photo__c,Rating__c,Album_Rating__C,genre__r.Name__c,User__r.Name__c from Album__C WHERE User__r.Name__c LIKE : getSelected+'%']));
             
            } 
            
           if(getSelected!='' || getSelected!=NULL && getValue == 'Album_Rating__C')
            {
                  setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                      [select id,Name,Cover_Photo__c,Rating__c,Album_Rating__C,genre__r.Name__c,User__r.Name__c from Album__C WHERE Album_Rating__C LIKE : getSelected+'%']));
             
            } 
           }
           return setCon; 
        }
        set;
    }

public List<Album__C> getAlbums() {
         setCon.setpagesize(2);
         return (List<Album__C>) setCon.getRecords();
    }
    
    
}