src/objects/Album__c.object
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/new_Album_Controller.cls
public class new_Album_Controller {
public Album__C album{get;set;}
    public Track__c track {get;set;}
public new_Album_Controller(){
    album = new Album__C();
    track= new Track__c();
}
public pageReference OldSave(){
    insert album;
        PageReference pgref = New PageReference('/apex/AddTracksToAlbumsPage?id='+album.ID);
           pgref.setRedirect(true);
           return pgRef;
    }
public pageReference NewSave(){
    insert album;
        PageReference pgref = New PageReference('/apex/NewTracksPage?id='+album.ID);
           pgref.setRedirect(true);
           return pgRef;
    }
    public pageReference Save(){
    insert album;
        PageReference pgref = New PageReference('/apex/musicHome');
           pgref.setRedirect(true);
           return pgRef;
    }
}