src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Cover_Photo__c</fullName>
        <label>Cover Photo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Users</label>
        <referenceTo>Users__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <label>Track Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Users__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>User ID-{0000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/musicHome_List_Controller.cls
public class musicHome_List_Controller {
    
    public String SearchText{get;set;} 
    public String option {get;set;}
    public string getAlbum;
    public String getValue;
    public string query;
    public List<Album__c> lstAlbums{get;set;}
    public Integer rec {get;set;}
    public Integer tot {get;set;}
    Public Integer count= 0;
    Public Integer LimitSize= 3;
    
    Public musicHome_List_Controller(Apexpages.StandardController controller){ 
    
        lstAlbums=new list<Album__c>();
    
        getAlbum = ApexPages.CurrentPage().GetParameters().get('query');
        getvalue = ApexPages.CurrentPage().GetParameters().get('s_by');
        
        if(SearchText=='' || SearchText == NULL){
            SearchText=getAlbum;
        }
        if(option=='' || option == NULL){
            option=getvalue;
        }
       
        //getting output by album name
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Name'){
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE Name LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            lstAlbums = Database.query(query);
            tot = [select count() from Album__C WHERE Name LIKE : getAlbum+'%'];
            }
       
        //getting output by track name
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Track__c.Name__C'){
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE Name LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            lstAlbums = Database.query(query);
            tot = [select count() from Album__C WHERE Name LIKE : getAlbum+'%'];
            }
       
        //getting output by Genre
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'genre__r.Name__c'){              
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE genre__r.Name__c LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            lstAlbums = Database.query(query);
            tot = [select count() from Album__C WHERE genre__r.Name__c LIKE : getAlbum+'%'];
            }
       
        //getting output by User
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'User__r.Name__c'){                
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE User__r.Name__c LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            lstAlbums = Database.query(query);
            tot = [select count() from Album__C WHERE User__r.Name__c LIKE : getAlbum+'%'];
            }
       
        //getting output by Rating
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Album_Rating__C'){                
           query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C Where Album_Rating__c  LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
           lstAlbums = Database.query(query);
           tot = [select count() from Album__C WHERE Album_Rating__C LIKE : getAlbum+'%'];
           }
    }
   
    //It is for Search Method
    public pageReference SearchAlbums(){        
   
    if(option == 'Name'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }     
   
    if(option == 'Track__c.Name__C')
    {
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+searchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }    
   
    if(option == 'genre__r.Name__c'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+searchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }
   
    if(option == 'User__r.Name__c'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }    
   
    if(option == 'Album_rating__C'){
       pageReference pgRef = new pageReference('/apex/musicHome_List?query='+SearchText+'&s_by='+option);
       pgRef.setRedirect(true);      
       return pgRef;
    }       
   
       else
       return null;       
    }    
    
    public List<Album__c> getAlbumsList(){
    
      List<Album__c> album = new List<Album__c>();
    
      if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Name')
      {
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE Name LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            album = Database.query(query);
     }
    
     //getting output by Track
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Track_Name__C')
        {              
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE genre__r.Name__c LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            album = Database.query(query);
         }
   
    //getting output by Genre
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'genre__r.Name__c')
        {              
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE genre__r.Name__c LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            album = Database.query(query);
         }
   
    //getting output by User
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'User__r.Name__c')
        {                
            query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C WHERE User__r.Name__c LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
            album = Database.query(query);
        }
   
    //getting output by Rating
        if((getAlbum!='' || getAlbum!=NULL) && getValue == 'Album_Rating__C')
        {                
           query = 'select id,Name,Cover_Photo__c,Album_Rating__c,Rating__C,genre__r.Name__c,User__r.Name__c,(SELECT id,Name,Track_Name__C FROM tracks__r) from Album__C Where Album_Rating__c  LIKE \''+getAlbum+'%\' LIMIT:limitsize OFFSET:count';
           album = Database.query(query);
         }    
        return album;
   
    }   
   
   //Pagination Methods   
   
     public Void updatePage() {
          limitsize=rec;
      }
    
    public PageReference Firstbtn() {
         count=0;
         return null;
        }
    public PageReference prvbtn() {
      count=count-limitsize;
      return null;
    }
   
     public PageReference Nxtbtn() {
         count=count+limitsize;
         return null;
        }

     public PageReference lstbtn() {
         count= tot - math.mod(tot,LimitSize);
         return null;
        }

        public Boolean getNxt() {
        if((count+ LimitSize) > tot)
         return true;
         else
           return false;
        }
     
     public Boolean getPrv() {
      if(count== 0)
          return true;
        else
          return false;
        }

}