src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Id__c</fullName>
        <label>Track_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks (User Album)</relationshipLabel>
        <relationshipName>Tracks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/addTracksToAlbums_Controller.cls
public class addTracksToAlbums_Controller{
    public Integer totalRecs = 0;
    public Integer count= 0;
    public Integer LimitSize= 5;
    public Track__C track {set;get;}
    public List<wrapTrack> wrapTrackList {get;set;}
    public List<wrapTrack> wrapSetController{get;set;}
    public List<Track__C> selectedTracks{get;set;}
    public List<Track__C> updatedTracks{get;set;}
        public Void updatePage(){
           wrapTrackList.clear();
           for(Track__C a: [Select id,Name,Album__c,Genre__C,Genre__r.Name__C,Track_Id__c From Track__C LIMIT:limitsize OFFSET:count]){
               wrapTrackList.add(new wrapTrack(a));
           }
        }
    public addTracksToAlbums_Controller(){
           totalRecs = [select count() from Track__C];
           track = new Track__c();
           updatedTracks = new list<Track__C>();
        	wrapSetController = new List<wrapTrack>();
           if(wrapTrackList == null) {
              wrapTrackList = new List<wrapTrack>();
              updatePage();            
           }          
        }
        public pageReference processSelected(){    
           updatedTracks = new list<Track__C>();
                   selectedTracks = new List<Track__C>(); 
           for(wrapTrack wrapTrackObj : wrapTrackList) {
               if(wrapTrackObj.selected == true) {
                  selectedTracks.add(wrapTrackObj.acc);
               }
           } 
           for(Track__c cc: [Select id,Name,Album__c,User_Album__c,Genre__C,Track_Id__c From Track__C where id IN: selectedTracks]){            
               if(cc.Album__c != null){          
               		cc.User_Album__c = track.album__C;
               }
               else{
                   cc.Album__c = track.album__C;
               }
              updatedTracks.add(cc); 
           }
           upsert updatedTracks;        
           pageReference pgref = New pageReference('/apex/musicHome');
           pgref.setRedirect(true);
           return pgRef;
        }    
        public PageReference Firstbtn(){
           count=0;
           updatePage();
           return null;
        }
        public PageReference prvbtn(){          
           count=count-limitsize;
           updatePage();
           return null;
        }
        public PageReference Nxtbtn(){    
           count=count+limitsize;
           updatePage();
           return null;
        }
        public PageReference lstbtn(){
           count= totalrecs - math.mod(totalRecs,LimitSize);
           updatePage();
           return null;
        }
        public Boolean getNxt(){
           if((count+ LimitSize) > totalRecs)
               return true;
                else
               return false;        
        }
        public Boolean getPrv(){
           if(count== 0)
                return true;
                 else
                return false;     
        }
}