src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Cover_Photo__c</fullName>
        <label>Cover Photo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Users</label>
        <referenceTo>Users__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Genre</label>
    <nameField>
        <displayFormat>Genre-ID-{0000}</displayFormat>
        <label>Genre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Track_Id__c</fullName>
        <label>Track_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <label>Track Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Album__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Tracks (User Album)</relationshipLabel>
        <relationshipName>Tracks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TrackId-{00000}</displayFormat>
        <label>TrackId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>UID-{0000}</displayFormat>
        <label>UserId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Users__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>User ID-{0000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Tracks_Controller.cls
public class Tracks_Controller {   
public string albumName{get;set;}
public Album__C albm{get;set;}
public List<Album__c> albums {get;set;}
public List<Track__C> lstTracks{get;set;}
public Integer rating {get; set;}

public Tracks_controller(){
    albumName = ApexPages.CurrentPage().GetParameters().get('album');
    albm = [select id,Cover_Photo__C,Name,User__r.Name__c,genre__r.Name__c from Album__C Where Name =:albumName];
    
}

public List<Track__C> getAllTracks(){
    lstTracks = [Select id,Name,Track_Name__C,Genre__c,Track_Id__c,User_Album__r.Name,Album__r.Name,Album__r.Cover_Photo__c From Track__c where Album__r.name =: albumName OR User_Album__r.Name =: albumName];
    return lstTracks;
}
public void Albums(){        
         if(albumName!='' || albumName!=NULL)
        {
          albums = [select id,Name,User__c,Rating__c,Cover_Photo__c,genre__r.Name__c,User__r.Name__C from Album__C Where User__r.Name__C Like : albm.User__r.Name__C];
        }      
    }
    public PageReference tracksSelected(){
        PageReference pgref = New PageReference('/apex/AddTracksToAlbumsPage?id='+albm.ID);
           pgref.setRedirect(true);
           return pgRef;
    }
    
    public  void UpdateAlbum(){        
       albm.Album_Rating__c = String.valueof(rating);
       update albm;
    /*   PageReference pgref = New PageReference('apex/TracksPage?album={!albm.name}');
           pgref.setRedirect(true);
           return pgRef;*/
        }
}