src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company or Organisation</description>
        <inlineHelpText>Company Name or Organisation Name</inlineHelpText>
        <label>Company Name</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain(Industry)</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <inlineHelpText>Product/Service</inlineHelpText>
        <label>Product</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Domain__c</fullName>
        <inlineHelpText>Sub Domain/Related Industry/Market</inlineHelpText>
        <label>Sub Domain</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Home_Controller.cls
public class Home_Controller {

    public PageReference allAlbums() {
        return null;
    }


    public Home_Controller() {

    }

public String SearchText{get;set;}
public List<Company__c> lstCompanies{get;set;}
public String option {get;set;}
    public Home_Controller(ApexPages.StandardController controller) {

    }

    public pageReference searchCompanies()
    {
        
    if(option == 'Company_Name__C')
    {
       pageReference pgRef = new pageReference('/apex/ListPage?query='+SearchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }
     
    if(option == 'Product__C')
    {
       pageReference pgRef = new pageReference('/apex/ListPage?query='+searchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }
    
    if(option == 'Domain__C')
    {
       pageReference pgRef = new pageReference('/apex/ListPage?query='+searchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }
    
    if(option == 'Sub_Domain__C')
    {
       pageReference pgRef = new pageReference('/apex/ListPage?query='+SearchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }
    
    if(option == 'Locality__C')
    {
       pageReference pgRef = new pageReference('/apex/ListPage?query='+SearchText+'&s_by='+option);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
      
       return pgRef;
    }
       
       else
       return null;
       
    }
   
    
}