src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company or Organisation</description>
        <inlineHelpText>Company Name or Organisation Name</inlineHelpText>
        <label>Company Name</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain(Industry)</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>teeee__c</fullName>
        <label>teeee</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <recordTypes>
        <fullName>Esdm</fullName>
        <active>true</active>
        <label>Esdm</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ListPage1.cls
public class ListPage1 {

public String SearchText{get;set;}
public string getCompany;
public string getCategory;
public string query;

public List<Company__c> lstCompanies{get;set;}
   
//Constructor
   public ListPage1() {
        
      
        lstCompanies = new list<Company__c>();
        
        getcompany = ApexPages.CurrentPage().GetParameters().get('CompanyName');
        getCategory = ApexPages.CurrentPage().GetParameters().get('cat');
         
        
        if(getCompany!='' || getCompany!=NULL)
            {
    
            query = 'SELECT id, Company_Name__c,Domain__C,Logo__c,teeee__c from Company__c WHERE Company_Name__c LIKE \''+getcompany+'%\'';
            lstCompanies= Database.query(query);
           }
           
        
        
        if(getCategory =='ESDM')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,Logo__c,teeee__c from Company__c WHERE Domain__C LIKE \'' +getCategory + '%\'';
            lstCompanies= Database.query(query);
             system.debug('++++++'+lstCompanies);
        }
        if(getCategory =='Plastic')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,Logo__c,teeee__c from Company__c WHERE Domain__C LIKE \'' +getCategory + '%\'';
            lstCompanies= Database.query(query);
            
        }
        if(getCategory =='Govt Bodies')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,Logo__c,teeee__c from Company__c WHERE Domain__C LIKE \'' +getCategory + '%\'';
            lstCompanies= Database.query(query);
            
        }
        if(getCategory =='VCs')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,Logo__c,teeee__c from Company__c WHERE Domain__C LIKE \'' +getCategory + '%\'';
            lstCompanies= Database.query(query);
            
        }
        if(getCategory =='IT Services')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,Logo__c,teeee__c from Company__c WHERE Domain__C LIKE \'' +getCategory + '%\'';
            lstCompanies= Database.query(query);
            
        }
        if(getCategory =='')
        {
            query = 'SELECT id,Domain__C, Company_Name__c,teeee__c,Logo__c from Company__c';
            lstCompanies= Database.query(query);
              
        }
       
    }
                          
    public pageReference SearchCompanies()
    {
      
        pageReference pgRef = new pageReference('/apex/ListPage?companyName='+SearchText);
        pgRef.setRedirect(true);
        return pgRef;
    
    }
    
  
}