src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company or Organisation</description>
        <inlineHelpText>Company Name or Organisation Name</inlineHelpText>
        <label>Company Name</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ItecHomeClass.cls
public class ItecHomeClass {
    public String SearchText {get;set;}
public List<Company__c> companieslist{get;set;}
    public ItecHomeClass(ApexPages.StandardController controller) {

    }
    
    public void SearchCompanies(){
        if(SearchText!='' && SearchText!=NULL){
        SearchText += '%';
        companieslist = [select id, Company_Name__c,Logo__c from Company__c where Company_Name__c LIKE : SearchText];
    }
    }
    public Pagereference ListPage(){
        PageReference pageRef = new PageReference('/apex/ITECListPage?='+SearchText);
        pageRef.setRedirect(true);
        return pageRef;
    }

}