src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company or Organisation</description>
        <inlineHelpText>Company Name or Organisation Name</inlineHelpText>
        <label>Company Name</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain(Industry)</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <recordTypes>
        <fullName>Esdm</fullName>
        <active>true</active>
        <label>Esdm</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Home1_Controller.cls
public class Home1_Controller {
public String SearchText{get;set;}
public List<Company__c> lstCompanies{get;set;}
    
    public pageReference searchCompanies()
    {
   
       pageReference pgRef = new pageReference('/apex/ListPage?companyName='+SearchText);
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
       return pgRef;
    }
    
    public pageReference SearchESDM(){
        lstCompanies = [select Company_Name__C,Logo__C,Domain__C from Company__C Where Domain__C LIKE 'ESDM'];
        pageReference pgRef = new pageReference('/apex/ListPage?Category='+'ESDM');
       system.debug('======='+SearchText);
       pgRef.setRedirect(true);
       return pgRef;
    }
}