src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company or Organisation</description>
        <inlineHelpText>Company Name or Organisation Name</inlineHelpText>
        <label>Company Name</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain(Industry)</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employees__c</fullName>
        <label>Employees</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head__c</fullName>
        <label>Head</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locality__c</fullName>
        <label>Locality</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <inlineHelpText>Product/Service</inlineHelpText>
        <label>Product</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <inlineHelpText>Location of the industry</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Domain__c</fullName>
        <inlineHelpText>Sub Domain/Related Industry/Market</inlineHelpText>
        <label>Sub Domain</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Site__c</fullName>
        <label>Web Site</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>Email-ID-{0000}</displayFormat>
        <label>E ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DetailPageController.cls
public class DetailPageController {

public string SearchText{get;set;}
public string getCompanyName{get;set;}
public Company__C comp{get;set;}
  
    public DetailPageController(ApexPages.StandardController controller) {
        getCompanyName = ApexPages.CurrentPage().GetParameters().get('Comapany');
            
            
        if(getCompanyName!='' || getCompanyName!=NULL)
        {
    
            String query = 'SELECT id, Company_Name__c,Logo__c,City__c,Contact__c,Domain__c,Sub_Domain__c,Email__c,Employees__c,Product__c,Position__c,Head__c,Street__c,Locality__c,Revenue__c,Web_Site__c from Company__c Where Company_Name__C =: getcompanyName';
            comp= Database.query(query);
            system.debug('Company is::::: ' + comp.Company_Name__C);
           
        }
        }
        
        public pageReference searchCompanies(){
       
           pageReference pgRef = new pageReference('/apex/ListPage?companyName='+SearchText);
           system.debug('======='+SearchText);
           pgRef.setRedirect(true);
           return pgRef;
           
    }
    
}