src/objects/User__c.object
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>UID-{0000}</displayFormat>
        <label>UserId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Profile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>Users</label>
        <referenceTo>Users__c</referenceTo>
        <relationshipLabel>User Profiles</relationshipLabel>
        <relationshipName>User_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>User Profile</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Users__c.object
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>User ID-{0000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Add_Users_Controller.cls
public class Add_Users_Controller {
    Public blob picture {set;get;}
    public Users__c user{get;set;}
    public User_Profile__c profile {get;set;}
    public Add_Users_Controller(){
      user= new Users__c();
        profile= new User_Profile__c();
    }
    public pageReference save(){
       insert user;
       profile.User__c=user.Id;
        upsert profile;
        if (picture != null) {
            Attachment attachment = new Attachment();
            attachment.body = picture;
            attachment.name = 'User_Profile_' + profile.id + '.jpg';
            attachment.parentid = profile.id;
            attachment.ContentType = 'application/jpg';
            insert attachment;
            profile.Picture_Path__c = '/servlet/servlet.FileDownload?file='+ attachment.id;
            update profile;
    }
        pageReference pgref = New pageReference('/apex/musicHome');
    	pgref.setRedirect(true);
    	return pgRef;
    }
}